# Generated by Django 6.0.6 on 2026-06-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('mid_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bands', to='core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_bands', to='core.currency')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bands', to='core.jobtitle')),
            ],
            options={
                'ordering': ['job_title__title', 'country__name'],
                'unique_together': {('job_title', 'country')},
            },
        ),
    ]
