# Generated by Django 6.0.6 on 2026-06-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Annual 2026"', max_length=200)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_pct', models.DecimalField(decimal_places=2, help_text='Budget increase percentage for this department', max_digits=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_budgets', to='core.department')),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_budgets', to='reviews.reviewcycle')),
            ],
            options={
                'unique_together': {('review_cycle', 'department')},
            },
        ),
        migrations.CreateModel(
            name='SalaryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_salary', models.DecimalField(decimal_places=2, help_text='Snapshot of employee salary at cycle creation', max_digits=18)),
                ('proposed_increase_pct', models.DecimalField(decimal_places=2, default=0, help_text='Proposed increase percentage, editable by HR Manager', max_digits=5)),
                ('proposed_salary', models.DecimalField(decimal_places=2, help_text='Auto-calculated: current_salary * (1 + proposed_increase_pct / 100)', max_digits=18)),
                ('is_committed', models.BooleanField(default=False, help_text='True once this proposal has been applied to the employee record')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_proposals', to='employees.employee')),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='reviews.reviewcycle')),
            ],
            options={
                'ordering': ['employee__employee_code'],
                'unique_together': {('review_cycle', 'employee')},
            },
        ),
    ]
