/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BandsRouteImport } from './routes/bands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIdRouteImport } from './routes/employees.$id'

const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BandsRoute = BandsRouteImport.update({
  id: '/bands',
  path: '/bands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIdRoute = EmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bands': typeof BandsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bands': typeof BandsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bands': typeof BandsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employees/$id': typeof EmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bands' | '/dashboard' | '/employees' | '/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bands' | '/dashboard' | '/employees' | '/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/bands'
    | '/dashboard'
    | '/employees'
    | '/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BandsRoute: typeof BandsRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bands': {
      id: '/bands'
      path: '/bands'
      fullPath: '/bands'
      preLoaderRoute: typeof BandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$id': {
      id: '/employees/$id'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof EmployeesIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
  }
}

interface EmployeesRouteChildren {
  EmployeesIdRoute: typeof EmployeesIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesIdRoute: EmployeesIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BandsRoute: BandsRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
