# Generated by Django 6.0.6 on 2026-06-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, help_text='Auto-generated, e.g. EMP00001', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=300)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor')], default='full_time', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.country')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.department')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.jobtitle')),
                ('local_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.currency')),
            ],
            options={
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variable_bonus_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_date', models.DateField()),
                ('hr_note', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv_import', 'CSV Import'), ('salary_review', 'Salary Review')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='HR Manager', max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
