# Generated by Django 6.0.6 on 2026-06-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='review_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records', to='reviews.reviewcycle'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_salary_record',
            field=models.ForeignKey(blank=True, help_text='Points to the latest salary record for fast reads.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.salaryrecord'),
        ),
    ]
