# Generated by Django 6.0.6 on 2026-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('deactivate', 'Deactivate')], max_length=20)),
                ('entity_type', models.CharField(choices=[('employee', 'Employee'), ('salary_band', 'Salary Band'), ('review_cycle', 'Review Cycle'), ('currency', 'Currency')], max_length=30)),
                ('entity_id', models.CharField(max_length=100)),
                ('entity_label', models.CharField(help_text='Human-readable name or code of the entity', max_length=300)),
                ('field_changed', models.CharField(blank=True, max_length=200, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('acting_user', models.CharField(default='HR Manager', max_length=200)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
