# Generated by Django 6.0.6 on 2026-06-13 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('csv_import', 'CSV Import'), ('employee_export', 'Employee Export'), ('review_commit', 'Review Cycle Commit'), ('audit_export', 'Audit Log Export')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, help_text='Row counts, errors, etc.', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
